### ISSUE TITLE
Tag detail page should be split into Knessets

### ISSUE THREAD

**Issue by daonb** [hasadna/Open-Knesset#347]
The [tag page](https://oknesset.org/tags/%D7%AA%D7%97%D7%91%D7%95%D7%A8%D7%94%20%D7%A6%D7%99%D7%91%D7%95%D7%A8%D7%99%D7%AA/) should show only items in the current Knesset and should have links to the same view for previous Knessets.

**Comment by otadmor** [comment]
Im working on it and i have a question.
The Vote model has both meeting_number and bills_pre_votes/bills_first/Bill.objects.filter(approval_vote=self)
Bills have some proposals (which each one of them have a knesset_id) and first_committee_meetings/second_committee_meetings.
The questions are:
1) Should the link from knesset_id to Vote should be Vote.[bills_pre_votes/bills_first/Bill.objects.filter(approval_vote=self)].[PrivateProposal/KnessetProposal/GovProposal].knesset_id?
2) Vote.[bills_pre_votes/bills_first/Bill.objects.filter(approval_vote=self)].[first_committee_meetings/second_committee_meetings].committee.pk?
3) Vote.meeting_number.committee.pk?

Thanks.

**Comment by daonb** [comment]
@ofri can you take a look?

**Comment by daonb** [comment]
@ofri can you have a look? I'm having fun in France and won't be back till the 11th

**Comment by otadmor** [comment]
I have implemented the following connections for tag-knesset:
1. Tag-Bill Tag-Bill-Bill Date-Knesset End/Knesset Start
2. Tag-Vote Tag-Vote-Bill Pre Votes-Bill-Bill Date-Knesset End/Knesset Start
3. Tag-Vote Tag-Vote-Bill First Vote-Bill-Bill Date-Knesset End/Knesset Start
4. Tag-Vote Tag-Vote-Bill Approval Vote-Bill-Bill Date-Knesset End/Knesset Start
5. Tag-Vote Tag-Vote-Vote Time-Knesset End/Knesset Start
6. Tag-Committee Meeting Tag-Committee Meeting-Committee Meeting Date-Knesset End/Knesset Start

I have the following questions:
Does this make any sense? 
Any connections are missing for the Bill object?
Should the bill-vote connection should be reversed? (should the knesset number be determined by the vote's date or the bill's?) theres no problem changing.

I need approval of these connections before issuing a pull request.

**Comment by habeanf** [comment]
@daonb Help?

**Comment by ofri** [comment]
@otadmor 

for Votes, use only their time to filter (i.e., if vote.time is between knesset.start and knesset.end). Don't use the link from votes to bills (because this linking is heuristic, and can be wrong). If needed for performance (consult @habeanf or @MeirKriheli ) you can add a FK from Vote to Knesset (and populate it in a data migration using the votes time field).

For Bill - I think it should be presented if any of its related votes (pre-votes, first vote, approval vote) or any of its related meetings (first-meetings or second-meetings) or any of its proposals is in the relevant knesset. This means that a bill may appear in more than 1 knesset (which makes sense IMO).

**Comment by otadmor** [comment]
For Bill - what exactly the stage_date means? should i use it also?

**Comment by daonb** [comment]
Not sure, it's the date of the last stage update. Maybe sort by it?

**Comment by otadmor** [comment]
Does it means its one of (pre-votes, first vote, approval vote, first-meetings ,second-meetings)?

**Comment by daonb** [comment]
it's a date one of those stages you mention happened.

On 1 October 2015 at 01:49, otadmor <notifications@github.com> wrote:

> Does it means its one of (pre-votes, first vote, approval vote,
> first-meetings ,second-meetings)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hasadna/Open-Knesset/issues/347#issuecomment-144567800>
> .
>



-- 



http://tuzig.com - Building Fires in The Cloud

**Comment by otadmor** [comment]
I noticed some bills have stage_date with older date than one of the proposals. I wanted to know if:
1) Should proposal date (knesset_bill.proposals.date) should be relevant for a knesset with these dates?
2) for the later proposal date than the stage date - I see why that happens in the code. The reason is some return phrases in the middle of update_stage - for example - if approval date exists then the proposal date will not be taken in account for the stage date. I wanted to know if this is the expected behavior (because we want the approval vote to be the stage date) or not (because we dont expect proposals after the approval vote or if there should not be a "return")?

Thanks.

**Comment by OriHoch** [comment]
fixed and deployed

**Comment by daonb** [comment]
¸.·´¯`·.´¯`·.¸¸.·´¯`·.¸><(((º>

On 9 November 2015 at 21:30, Ori Hoch <notifications@github.com> wrote:

> Closed #347 <https://github.com/hasadna/Open-Knesset/issues/347>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hasadna/Open-Knesset/issues/347#event-459237083>.
>



-- 



http://tuzig.com - Building Fires in The Cloud
