### ISSUE TITLE
plenum scraping process should deal properly with knesset returning 404 error

### ISSUE THREAD

**Issue by habeanf** [hasadna/Open-Knesset#379]
Some protocols are not available: https://oknesset.org/plenum/10216/

**Comment by OriHoch** [comment]
if I run the following command locally, it adds all the missing protocols:

./manage.py parse_plenum_protocols --download --parse

this command is supposed to run in a cronjob on the server

so:

1. please check if the job is scheduled, and when does it run
2. try to run it with -v2 parameter to get debugging info and see if there is a problem

**Comment by OriHoch** [comment]
The reason is that the plenum scraping process fails when knesset returns 404 page for a plenum file:

The failure occurs when running antiword on the html error page - in that case antiword returns an error that file is not a word document - and we raise an exception in that case so that entire scraping process stops.

2 things should be fixed here:

1. detect 404 error and ignore that meeting (to try again later)
2. detect antiword error that file is not word document - ignore that meeting and continue running scraper
