### ISSUE TITLE
In a single committee view - show only 10 meetings in general view

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#565]
בעברית, הגבילו את מספר היחידות שניתן לראות בכל קטגוריה:
- ישיבות קרובות: מקסימום עשר 
- ישיבות מהן טרם פורסם פרוטוקול: מקסימום עשר
- ישיבות אחרונות: מקסימום עשר

**Comment by morchickit** [comment]
@alonisser - can you take this?

**Comment by alonisser** [comment]
yap

**Comment by alonisser** [comment]
@morchickit 
1. Can you provide an example link?
2. Is the expected behavior to committees without protocols to provide a "more" link like "last committees" (a little more expensive in time)

**Comment by morchickit** [comment]
1. ראה ועדת הרווחה של הכנסת - 
https://oknesset.org/committee/10/

2. Committees without protocols see here - 
https://oknesset.org/committee/1/
(I think we should change אין to - אין כרגע מידע זמין

**Comment by alonisser** [comment]
@morchickit @OriHoch  Can  you please explain the current logic of "protocol_not_yet_published_list" meeting list?

Looks like the current implemantion just takes committee events from a given timeframe (day +  1 from last committee meeting to now) with no check if it actually has a protocol
Along the lines of:
```python
events.filter(when__gt=start_date, when__lte=end_date)
```

Is this the expected behavior or something else?

**Comment by alonisser** [comment]
Nevermind, just understood this is an overloaded term here.  missing protocol refers in this part to mettings we don't have any data about the actual meeting, and in another place it's in a meeting that has a missing protocol

**Comment by OriHoch** [comment]
deployed, looks ok
