### ISSUE TITLE
Add MK attendance in committees meetings manually 

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#596]
Dear content team - adopt a committee!

Take one and add the MK that attended manually to the meetings they were at!

Please write here which committee you took!

**Comment by morchickit** [comment]
@maryLoi - any new content volunteers are welcome to do this!

**Comment by Dorsrebernik** [comment]
Hi, in the Shkifut committee, 
cannot remove MK (Shai Piron) from list: https://oknesset.org/committee/meeting/11655/ 
Also, drop-down list does not work when adding/removing MKs: 
https://oknesset.org/committee/meeting/11654/

**Comment by morchickit** [comment]
There was a drop down? :-o

**Comment by Dorsrebernik** [comment]
Need to remove Yael Dayan here: https://oknesset.org/committee/meeting/11571/
remove David Bitan from here: https://oknesset.org/committee/meeting/11654/
remove Menachem Begin (lolol :)) from here: https://oknesset.org/committee/meeting/10146/

**Comment by Dorsrebernik** [comment]
Finished adding MKs manually to committees: 
שקיפות
ועדה מיוחדת לזכויות הילד
ועדה מיוחדת לדיון בהצעת חוק השידור הציבורי
קידום מעמד האשה

**Comment by morchickit** [comment]
@OriHoch - yes, the way the algorithm is working now is not good (see the Menachem Begin easter egg)

**Comment by morchickit** [comment]
and Dror is on a roll! Well done @Dorsrebernik !

**Comment by alonisser** [comment]
@morchickit @Dorsrebernik  I see the drop down working.. it waits for a first letter type to start, because it was meaning less just guessing from 120 . Maybe hard refresh to the web page would help since some js changes were done there. Please update if this isn't working, with what browser are you using ,etc

**Comment by OriHoch** [comment]
I added an option to semi-automatically set attendance, you can run it from admin on specific meetings. It deletes all existing members and re-adds them automatically from the protocol.

See slack (oknesset channel) for an image which describes how to do it..

I guess you would want to use that from now on instead of manually, but still some validation should be done of this automatic process.

**Comment by OriHoch** [comment]
@morchickit @RacheliRoval - could you update about the status? is everything updated now?

**Comment by morchickit** [comment]
So, I added alt names, but I can't run the re-parse for every committee. I am assuming this is correct, and will add a message (in a different topic) why attendance can be problematic.
