### ISSUE TITLE
In the comparison page, the number of proposed bills per MK is incorrect

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#629]
ליאיר לפיד מסומן במערכת כנסת פתוחה 26, בעוד במערכת הכנסת יש לו 33 מאז תחילת הכנסת ה-20 ו.
https://oknesset.org/member/by/bills_proposed/

הערה לעתיד, מערכת הצעות החוק של הכנסת היא איטית, מיושנת, ובעיקר הייתי צריכה לעשות שם ספירה ידנית של מספר הצעות חוק... זה לוקח הרבה זמן. התחלתי עם דב חנין, אבל זה שבר אותי ועברתי לדוגמא קטנה יותר. 
http://knesset.gov.il/privatelaw/Plaw_display.asp?lawtp=1
@alonisser

**Comment by alonisser** [comment]
Looks like the issue is with bill initiated in multiple knessets, I'll look into it

**Comment by alonisser** [comment]
example of our "bill" with 2 proposals. the source of this problem https://oknesset.org/bill/8783/

**Comment by alonisser** [comment]
@morchickit Looks good! stats page and bills page for mk are the same now in Open Knesset
 we are still not exactly the same with knesset for example Yair lapid
counted in knesset as 39 proposed in current knesset in Open Knesset only 37
One is a bill counted triple in knesset and only twice in Open Knesset (:) ) :
הצעת חוק-יסוד: הממשלה (תיקון - הגבלת כהונת ראש הממשלה לשתי תקופות כהונה רצופות)
and the other one is listed in knesset as yair lapid as one of the proposers while in Open Knesset he is not listed as one. I don't know exactly why, but either a scraping or a human mistake, not the algorithm for filtering and presenting this time. So this bug is finally closed
