### ISSUE TITLE
Make sure all MK's are allocated in the right committees

### ISSUE THREAD

**Issue by morchickit** [hasadna/Open-Knesset#637]
היו כל כך הרבה שינויים במושב האחרון, שיכול להיות שפספסנו.

**Comment by OriHoch** [comment]
@noamelf does your changes to committees scraper handle this?

**Comment by RacheliRoval** [comment]
@morchickit, I started with ועדת החוץ והביטחון and I have some comments:
1.  אורן חזן, אריה דרעי,זאב אלקין, זהבה גלאון, יצחק הרצוג, מירי רגב, משה גפני ורוברט אילטוב רשומים אצלנו כחברי ועדה אבל לא באתר הכנסת. בדקתי באופן אישי באתר הכנסת לגבי כל אחד מהם ונראה שהם היו חברי ועדה באיזשהו שלב בכנסת ה-20 אך כנראה שכבר לא. בינתיים אני משאירה אותם כחברי ועדה לפי מה שסיכמנו אתמול, אבל צריך לשקול מה עושים בהמשך כיוון שזה מביא לכך שיש המון חברים בועדה שהיא גם ככה ועדה ענקית.
2.  It seems like there is a problem with the statistics section, maybe due to the fact the protocols are not public. For example, Tzahi Hanegbi which is the chairperson of the committee is standing on 0% presence. Doesn't make sense...

**Comment by alonisser** [comment]
@RacheliRoval  בעניין ועדת חוץ ובטחון
בדף הזה באתר הכנסת
https://www.knesset.gov.il/committees/heb/CommitteeHistoryByComAndKnes.asp?com=4&kn=20
יש פירוט בנושא הזה של מתי כל אחד מאלו התחיל וסיים להיות חבר ועדה

@morchickit 
זו דוגמא לעוד שגיאת מידול אצלנו - חבר ועדה להבנתי כרגע, תקני אותי אם פיספסתי משהו
הוא בוליאני, או שאתה חבר או שאתה לא, והמצב האמיתי מסתבר הוא שחברות בועדה היא סטטוס שיש לו תקופות (וגם סוגים שונים, של חבר או מחליף, אבל זה ניחא)

אם אני מבין נכון אשרי ואפתח באג מסודר על זה

**Comment by morchickit** [comment]
@alonisser - You are right, I just raised that issue with the team on Monday night (with @OriHoch as well) if you can open a bug about it it would be great

**Comment by RacheliRoval** [comment]
סיפור דומה בועדה המיוחדת לדיון בהצעת חוק להתחדשות עירונית ובסעיפים מהצעת חוק התוכנית הכלכלית: היה שינוי די משמעותי בועדה לאורך הקדנציה. הוספתי את הח״כים שהיו חסרים אך עדיין נותרו 4 ח״כים שכיהנו במהלך הקדנציה אך נכון להיום אינם חברי ועדה: בצלאל סמוטריץ׳, יואב בן צור, מאיר כהן ורוברט אילטוב. ֿכדאי באמת לחשוב איך פותרים את העניין.

**Comment by RacheliRoval** [comment]
@morchickit, I'm done with this issue. I checked all the Va'adot and added the necessary  MK's in django, so It's fully updated now.
In each Va'ada I wrote to myself which MK's were replaced during this period but didn't remove them from the list.

**Comment by morchickit** [comment]
Great Racheli! You can close this issue now. :)

**Comment by alonisser** [comment]
@morchickit I opened the new issue https://github.com/hasadna/Open-Knesset/issues/643
