### ISSUE TITLE
[Question] what's the meaning of laws_bill.stage column?

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#834]
האם סטטוס הצ"ח זה laws_bill.stage?
ואיך יודעים מה המשעות של המספרים?

**Comment by alonisser** [comment]
סטטוס של Bill - שזה לא הצעת חוק ממש אלא קונסטרוקט שלנו
In laws.enums.. 
class BillStages(Enum):
    UNKNOWN = u'?'
    FROZEN = u'0'
    PROPOSED = u'1'
    PRE_APPROVED = u'2'
    FAILED_PRE_APPROVAL = u'-2'
    CONVERTED_TO_DISCUSSION = u'-2.1'
    IN_COMMITTEE = u'3'
    FIRST_VOTE = u'4'
    FAILED_FIRST_VOTE = u'-4'
    COMMITTEE_CORRECTIONS = u'5'
    APPROVED = u'6'
    FAILED_APPROVAL = u'-6'

**Comment by alonisser** [comment]
I've moved every place I saw the number to use the enum, maybe there are more I missed

**Comment by alonisser** [comment]
But as I said and wrote multiple times in multiple places, mostly ignored. THERE IS NO BILL CONSTRUCT IN KNESSET. This is a pure invention by us. Sometimes useful, guess driven since we are grouping together DIFFERENT Proposals  FROM DIFFERENT KNESSETS OR FROM THE SAME KNESSET by vague heuristics. Surprisingly enough this seems to be working quite well for some cases. 

What the NEW Hakika api adds is something similar, but not as broad as ours. they show name changes, and explicit merging and branching of laws. But not previous knesset (unless continues, quite rare) and not if there wasn't an official merging (also, quite rare from Private Proposals)

**Comment by OriHoch** [comment]
@maryLoi ^
